### ISSUE TITLE
support custom excerpt

### ISSUE THREAD

**Issue by juliangruber** [metalsmith/metalsmith-excerpts#3]
instead of taking the first paragraph it would be great to be able to supply a custom excerpt

**Comment by webketje** [comment]
This has actually been implemented a while ago, see [fixtures/no-mutation](https://github.com/metalsmith/metalsmith-excerpts/blob/master/test/fixtures/no-mutation) & test https://github.com/metalsmith/metalsmith-excerpts/blob/master/test/index.js#L118
